import matplotlib.pyplot as plt
import pandas as pd

vgs_data = pd.read_csv("C:/Users/Erdem/python kodları/Data_Visualization/videoGameSaleData/vgsales.csv")
print(vgs_data.head())

vgs_data_grouped = vgs_data.groupby('Platform').agg({'Global_Sales':'sum'}).sort_values('Global_Sales', ascending = False).head(10)
print(vgs_data_grouped)
#Release Dates are up to 2017, keep that in mind.


colors_list = ['gold', 'yellowgreen', 'lightcoral', 'lightskyblue', 'lightgreen', 'pink', 'mediumorchid', 'peru', 'cyan', 'maroon']
explode_list = [0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.1] # ratio for each continent with which to offset each wedge.

vgs_data_grouped['Global_Sales'].plot(kind='pie',
                            figsize=(15, 9),
                            autopct='%1.1f%%', 
                            startangle=90,    
                            shadow=True,  
                            label='',           # remove column name from the left of the chart.
                            labels=None,        # turn off labels on pie chart
                            pctdistance=0.75,    # the ratio between the center of each pie slice and the start of the text generated by autopct 
                            colors=colors_list,  # add custom colors
                            explode=explode_list, # 'explode' lowest 3 continents
                            textprops={'fontsize': 15}
                            )

# scale the title up by 12% to match pctdistance
plt.title('Top 10 Global Video Game Sales by Platform', y=1, color = 'red', fontsize = 20) 

plt.axis('equal') 

# add legend
plt.legend(labels=vgs_data_grouped.index, loc='upper left', prop={'size': 15}) 

plt.savefig('videoGamePie.png')
plt.show()